### ISSUE TITLE
using XGBoostLSS with reticulate and multi-target regression

### ISSUE THREAD

**Issue by p-schaefer** [StatMixedML/Py-BoostLSS#2] opened 2022-12-02 16:36 UTC
I'm entirely new to python and reticulate, so please bare with me, but I think I got most steps working correctly. I am running into two issues:
1 - trying to predict from a trained model,
2 - how do you generate the DMatix for multi-target regression

So far, I have:

```
xgboostlss.py<-reticulate::import("xgboostlss")

d1<-mtcars

y_out<-matrix(rnorm(nrow(d1)*3),ncol=3)
colnames(y_out)<-c("a","b",'c')

# I can't get the label argument to take more than 1 column here...
dtrain <- xgboostlss.py$model$xgb$DMatrix(as.matrix(head(d1,25)),label=head(y_out[,1],25)) 
dtest <- xgboost::xgb.DMatrix(as.matrix(tail(d1,7))) #label=tail(y_out[,1],7)

distribution = xgboostlss.py$distributions$Expectile
reticulate::py_set_attr(distribution,"stabilize",reticulate::r_to_py("MAD"))
reticulate::py_set_attr(distribution,"expectiles",reticulate::r_to_py(c(0.05,0.5, 0.95)))

params = list(eta= 0.05,                   
              max_depth= 5L,
              gamma= 3,
              subsample= 0.5,
              colsample_bytree= 0.5,
              min_child_weight= 100L
)

xgboostlss_model = xgboostlss.py$model$xgboostlss$train(params=reticulate::r_to_py(params),
                                                        dtrain=dtrain,
                                                        dist=distribution,
                                                        num_boost_round=reticulate::r_to_py(10L))

pred_expectile = xgboostlss.py$model$xgboostlss$predict(booster=xgboostlss_model, 
                                                        dtest=dtest, 
                                                        dist=distribution,
                                                        pred_type=reticulate::r_to_py("expectiles"))

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'PyCapsule' object has no attribute 'num_row'
```

Any help would be greatly appreciated.

**Comment by tim-habitat** [comment] 2022-12-06 13:28
@StatMixedML I did some digging and it seems that GPU training is not supported when passing a custom loss function. Perhaps if the loss function is coded in C or C++ and accessing the lower level api, but not from the python api...
Not sure it would even be multi-threaded due to `python` GIL, couple of people complaining about its slowness when passed custom functions.

**Comment by StatMixedML** [comment] 2022-12-06 13:52
@tim-habitat Ok nice, thanks! I am not sure then if it makes sense to further use catboost for multi-target regression settings...

**Comment by p-schaefer** [comment] 2022-12-06 14:03
> Ok I try to have the Dirichlet available soon, maybe some time early next week. Do you know of any publicly available Dirichlet dataset I can use?

@StatMixedML I'm not sure what your exact requirements are for a dataset, but the [DirichletReg](https://cran.r-project.org/web/packages/DirichletReg/) R package has a few small datasets that may be helpful.

**Comment by StatMixedML** [comment] 2022-12-07 08:34
@p-schaefer Thanks for the link. I was hoping to not use the Arctic-Lake dataset, but should be ok for an example notebook.

**Comment by p-schaefer** [comment] 2022-12-08 19:12
> @p-schaefer I have added the Dirichlet distribution with an example. Maybe you can try it with your dataset. Please make sure to first re-install the package, since I have made several changes.

@StatMixedML I think I've got the package installed correctly, but I'm having trouble getting it run with reticulate:

```
hp_dict = list(lr= c(0.00001,1),                   
              max_depth= c(1L,4L),
              sketch_outputs= c(1L,10L),
              subsample= c(0.5,1),
              colsample= c(0.2,1),
              lambda_l2=c(0,40),
              min_gain_to_split= c(1L,1000L)
)

dtrain<-list(
  X=data.frame(depth=DirichletReg::ArcticLake[,"depth"]),
  y=DirichletReg::ArcticLake[,1:3]
)

distribution = pyboostlss.py$distributions$DIRICHLET(D=r_to_py(as.integer(ncol(dtrain$y))))  
pyblss = pyboostlss.py$model$PyBoostLSS(distribution)

opt_param = pyblss$hyper_opt(params=r_to_py(hp_dict),
                             dtrain=r_to_py(dtrain),
                             use_hess=r_to_py(TRUE), 
                             sketch_method=r_to_py("proj"),
                             hp_seed=r_to_py(123L),                
                             ntrees=r_to_py(500L),                
                             n_trials=r_to_py(10L),              
                             max_minutes=r_to_py(120L),           
                             silence=r_to_py(FALSE))   

# Error in py_call_impl(callable, dots$args, dots$keywords) : 
# AttributeError: 'DataFrame' object has no attribute 'dtype'

```

**Comment by StatMixedML** [comment] 2022-12-13 09:22
@p-schaefer seems like this is a problem related to the reticulate package. Since I am not a reticulate-expert, I am afraid I don't have a solution for this. 

I suppose the error is thrown here https://github.com/StatMixedML/Py-BoostLSS/blob/7a7213f44f2533c7165c36f8e7fd79507c50dc4e/pyboostlss/distributions/MVN.py#L187

or here 

https://github.com/StatMixedML/Py-BoostLSS/blob/2f141e118b09e9dca9a2eaf7ec716950ae83fb01/pyboostlss/distributions/MVT.py#L196

or here
https://github.com/StatMixedML/Py-BoostLSS/blob/2f141e118b09e9dca9a2eaf7ec716950ae83fb01/pyboostlss/utils.py#L20

not sure how reticulate translates R-DataFrames into torch tensors.

**Comment by StatMixedML** [comment] 2022-12-14 14:06
closing this for now

**Closed by StatMixedML** 2022-12-14 14:06 UTC
Labels: enhancement
